### ISSUE TITLE
Upgrade Typescript from 4.8.4 to 4.9.4 to be able to use satisfies keyword

### ISSUE THREAD

**Issue by SirMishaa** [sachinraja/ts-lib-starter#121]
Hello,
I like your template a lot, that's a good work

I'd like to use the [satisfies keyword](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html) in my project. 

I just created a new project, but it seems to use an older version of Typescript, could we upgrade to the latest? I can do a PR for that. 
```bash
~/dev/hexa-node is 📦 v0.0.0 via  v19.3.0 on ☁️  (eu-central-1) 
❯ pnpm update --latest --interactive
? Choose which packages to update (Press <space> to select, <a> to toggle all, <i> to invert selection) … 
❯ ○ @types/node (dev) 18.11.9 ❯ 18.11.18 
  ○ dprint (dev)       0.32.2 ❯ 0.34.1   
  ○ eslint (dev)       8.27.0 ❯ 8.30.0   
  ○ tsup (dev)          6.4.0 ❯ 6.5.0    
  ○ typescript (dev)    4.8.4 ❯ 4.9.4    
  ○ vite (dev)          3.2.3 ❯ 4.0.3    
  ○ vitest (dev)       0.25.1 ❯ 0.26.2   

Enter to start updating. Ctrl-c to cancel.
```

Kind regards

**Comment by SirMishaa** [comment]
This is a bit the same for Vite, would be nice if we could upgrade to Vite 4 

Let me know what you think about it. I'd be glad to help if needed

**Comment by sachinraja** [comment]
Feel free to do a PR to update the deps. There shouldn't be any actual code changes needed here.
